[build]
  publish = "."
  functions = "netlify/functions"

[[headers]]
  for = "/data/sessions.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "no-cache"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"
